#ifndef __GL_OBJECTS_H__
#define __GL_OBJECTS_H__

typedef enum
{
	GLSL_LIGHT_SHADER,
	GLSL_LIGHT_MV,
	GLSL_LIGHT_PROJ,
	GLSL_LIGHT_LOCAL,
	GLSL_LIGHT_LIGHT0_POS,
	GLSL_LIGHT_LIGHT0_KD,
	GLSL_LIGHT_LIGHT1_POS,
	GLSL_LIGHT_LIGHT1_KD,
	GLSL_LIGHT_LIGHT2_POS,
	GLSL_LIGHT_LIGHT2_KD,
	GLSL_LIGHT_LIGHT3_POS,
	GLSL_LIGHT_LIGHT3_KD,
	GLSL_LIGHT_LIGHT4_POS,
	GLSL_LIGHT_LIGHT4_KD,

	GLSL_GENERIC_SHADER,

	GLSL_DISTANCE_SHADER,
	GLSL_DISTANCE_PROJ,
	GLSL_DISTANCE_MV,
	GLSL_DISTANCE_LOCAL,
	GLSL_DISTANCE_LIGHTPOS,

	TEXTURE_DISTANCE0,
	BUFFER_DISTANCE0,

	GLSL_MD5_GENVERTS_COMPUTE,

	NUM_OBJECTS
} ObjectNames;

extern uint32_t Objects[NUM_OBJECTS];

#endif
